[IV 21-22] Objetivo 2
Parka015/IV-Proyecto pull request #16
Opened 2021-11-30 21:16 UTC by NachoCarher

2021-12-01 07:59 UTC, JJ commented
No has hecho un PR a la asignatura.

2021-12-01 08:00 UTC, JJ commented
Y por favor, haz correctamente los mensajes de commit.

2021-12-02 12:56 UTC, NachoCarher commented
Ya he hecho PR a la asignatura

2021-12-03 12:00 UTC, NachoCarher commented
@Parka015 para que el PR estuviese completo al 100% sería necesario que le asignases los issues en los que se trabaja y el milestone al que se asocian, ya que es algo que no puedo modificar yo. Está todo referenciado en los commits realizados.

2021-12-04 07:38 UTC, Parka015 commented
> @Parka015 para que el PR estuviese completo al 100% sería necesario que le asignases los issues en los que se trabaja y el milestone al que se asocian, ya que es algo que no puedo modificar yo. Está todo referenciado en los commits realizados.

Por alguna razón, no me deja, esta mencionado dentro del issue #7 que ese es el issue sobre el que tiene que trabajar, prueba a hacer un comentario en dicho issue para ver si no me deja asignar por eso

2021-12-04 07:41 UTC, Parka015 requested changes
El issue #7  es el único del que debes encargarte, por lo tanto las demás issues y el archivo de características.py ya lo estoy desarrollando yo

2021-12-04 18:17 UTC, Parka015 commented
@NachoCarher aunque ya lo he corregido, recuerda asignar los PR  que hagas a un PMV . Si no sabes como se hace es al principio de la pagina del PR (esta por ejemplo) en el lado derecho donde viene Assignees, labels, Projects, **Milestone** ... Le pinchas y selecciones el Milestone.
Este PR en principio esta asociado al M0 asi que lo dejo así

2021-12-10 11:53 UTC, NachoCarher commented
@Parka015 sé que hay que asignar los PR a un issue y milestone, pero en este caso, como el PR está siendo a tu repo, no es tarea mía realizar esa asignación. Básicamente porque no me deja, sólo tú tienes autorización para hacerlo, y por eso te he pedido que los asignes. Ya he visto que lo has actualizado. Gracias.

2021-12-10 13:08 UTC, JJ reviewed
Independientemente de lo que diga @Parka015 , deberías darle una vuelta a cómo implementar los issues que se han creado.

2021-12-10 13:08 UTC, JJ commented on source/caracteristicas.py
> +        if self.genero == 1.0
Esta no es la mejor forma de hacer esto. Y en todo caso, no hay que meter código en este objetivo.

2021-12-11 11:16 UTC, Parka015 commented
> @Parka015 sé que hay que asignar los PR a un issue y milestone, pero en este caso, como el PR está siendo a tu repo, no es tarea mía realizar esa asignación. Básicamente porque no me deja, sólo tú tienes autorización para hacerlo, y por eso te he pedido que los asignes. Ya he visto que lo has actualizado. Gracias.

No sabía que no te dejaba, fallo mío entonces

2021-12-13 19:17 UTC, NachoCarher commented on source/caracteristicas.py
> +        if self.genero == 1.0
Se quería que los géneros fuesen valores reales y aquí implementé una correlación entre el nombre del género y su valor. En su defecto, no implemento código y lo dejo como estaba, tan solo con el return de su valor original.

2021-12-17 19:05 UTC, JJ commented
Los mensajes de commit nunca son "actualizo no sé qué" Di lo que haces y por qué.

2021-12-17 19:07 UTC, JJ requested changes
Después del último merge no tengo muy claro qué has hecho y como una clase que sólo tiene un ID trata de identificar el éxito de una serie.

2021-12-17 19:07 UTC, JJ commented on source/serie.py
> +Class serie:
No entiendo muy bien. Al final, ¿esto es todo lo que has hecho?

2021-12-17 21:36 UTC, NachoCarher commented
@JJ Se soluciona el issue en el que se indica que una serie debe de tener un identificador único. Y el éxito de una serie se podrá predecir en base a los atributos que hay ya en la clase características. Toda la estructura de clases inicial ya está creada y el fichero .yaml tiene especificadas las entidades objeto/valor. No considero que sea necesario implementar más cosas y se avanza en la consecución de #3 y de #7.

2021-12-21 10:39 UTC, JJ commented
> @JJ Se soluciona el issue en el que se indica que una serie debe de tener un identificador único. Y el éxito de una serie se podrá predecir en base a los atributos que hay ya en la clase características. Toda la estructura de clases inicial ya está creada y el fichero .yaml tiene especificadas las entidades objeto/valor. No considero que sea necesario implementar más cosas y se avanza en la consecución de #3 y de #7.

¿Creando una clase con un ID? De veras, tendrás que currártelo un poquitín más. O haces alguna clase más, o clarificas qué necesita más esa clase, o haces algo que puedas usar en la lógica de negocio. Tienes varias opciones más para avanzar en el PMV.

2021-12-23 10:56 UTC, NachoCarher commented
@JJ he tratado de esclarecer aún más que era necesario para la clase serie.py. Para alcanzar #3 se requiere calcular por medio de un algoritmo determinado y desarrollado en otro módulo la predicción de la valoración de una serie. Por lo que esta estimación obtenida en función de las características es un atributo de cada serie y se puede asignar rápidamente mediante el identificador único previamente implementado.

2021-12-23 12:34 UTC, JJ requested changes
De veras, tendrás que hacer algo más si quieres superar el objetivo. NO se trata de que haya un mínimo de código a desarrollar, se trata de que es imposible que una serie sólo necesite eso.
Adicionalmente, usa las mejores prácticas de Python en los identificadores.

2021-12-23 12:34 UTC, JJ commented on source/caracteristicas.py
> +
De veras, no hagáis esto. Genera ruido en la corrección y no sirve para nada.

2021-12-23 12:34 UTC, JJ commented on source/serie.py
> +    self.prediccion_valoracion = -1 # Éxito estimado de una serie. Inicialmente nulo
De veras que una serie sólo tiene un identificador y una predicción de la valoración? ¿Nada más? ¿No tiene, no sé, el nombre de la serie o algo de eso? ¿Por qué importas KNN si no lo usas?

2021-12-23 14:29 UTC, NachoCarher commented
@JJ he solucionado lo respectivo al uso del import del módulo que no se utiliza. Las series es cierto que deben de contar con más atributos para poder trabajar con ellas correctamente y ser más fieles a la realidad, de manera que he implementado los esenciales. Y para facilitar el trabajo con varios objetos de la clase serie considero que es de gran utilidad contar con un catálogo que almacene todas ellas.

2021-12-23 16:32 UTC, JJ requested changes
Lo siento, no pasa este objetivo.

2021-12-23 16:32 UTC, JJ commented on source/catalogo.py
> +Class Catalogo:
De veras, ni siquiera estás intentando respetar la sintaxis de Python. Por no mencionar que tampoco añades código usando issues.

2021-12-27 18:26 UTC, NachoCarher commented
@JJ el código añadido en los commits anteriores en relación al catálogo usa el issue #23, el resto de modificaciones han trabajado sobre #7 y #8, y todo ello para avanzar en la consecución de #3 del M0. Y además ya no hay errores de sintaxis. 

Creo que ya está todo lo suficiente para completar este objetivo.

2021-12-29 17:32 UTC, JJ commented
Lo siento, @NachoCarher ,pero creo que dejé bien claro que una vez que se corrigieran los objetivos después del periodo lectivo, no se podían reenviar. El objetivo está no superado, como puedes ver en el fichero correspondiente. Puedes proceder a los siguientes.

2022-01-17 11:34 UTC, NachoCarher commented
@Parka015 Podrías darme tu feedback sobre la última modificación que hice por favor. Todo los implementado respeta la sintaxis de Python y se trabaja siempre sobre un issue aunque antes no los referenciaba, y ya es algo que siempre estoy teniendo en cuenta para los otros objetivos. Gracias.

2022-01-20 16:35 UTC, NachoCarher commented
@JJ como le comenté por Telegram, salvo los commits, creo que todo está corregido y se puede revisar

2022-01-23 14:32 UTC, Parka015 commented
> @Parka015 Podrías darme tu feedback sobre la última modificación que hice por favor. Todo los implementado respeta la sintaxis de Python y se trabaja siempre sobre un issue aunque antes no los referenciaba, y ya es algo que siempre estoy teniendo en cuenta para los otros objetivos. Gracias.

Veo que has mejorado en el aspecto de los commits, que explicas que hacen y los asocias a un issue.
En cuanto a lo realizado creo que hay atributos más que suficientes para la clase Serie pero sigue habiendo el mismo problema que te comenté hace tiempo, "debería aparecer un objeto de la clase características en la clase serie".
En lugar de un atributo predicción usa un atributo características

2022-01-24 22:25 UTC, NachoCarher commented
@Parka015 ya he solucionado el problema de los atributos que me comentaste. Gracias

2022-02-07 19:43 UTC, JJ requested changes
Lo siento, no superas este objetivo. Habría sido conveniente que lo compartieras con la clase para que te ayudaran, o simplemente que me hicieras caso a los comentarios anteriores.

2022-02-07 19:43 UTC, JJ commented on source/catalogo.py
> +  def __init__(self, series = []):
Ninguna parte de este código está asociada a ningún issue. Algunas partes están relacionadas con una HU que habla de "predicción". No tiene nada que ver con agregar o mostrar o eliminar. ¿Cómo identificas una serie? ¿Qué características tiene cada una?

2022-02-07 19:43 UTC, JJ commented on source/serie.py
> +from source.caracteristicas import Caracteristicas
Este no es un nombre que sigua las mejores prácticas. "source" no es un nombre correcto para un módulo, y hay que configurar el repo de forma que el nombre del módulo corresponda al del proyecto.

2022-02-07 19:43 UTC, JJ commented on source/serie.py
> +    self.identificador = iden                             # Codigo para identificar de forma unica cada serie
es mala práctica usar nombres diferentes para el atributo y el argumento.
Además, hay que usar la práctica común para indicar si son privados o no.

2022-02-07 19:43 UTC, JJ commented on source/serie.py
> +  def getLanzamiento(self):
Repetidamente hemos dicho en clase que *no* se deben poner getters y setters si no lo pide la lógica de negocio. Tampoco está justificado. Salvo alguna línea, el resto simplemente no corresponden a ningún issue. Tampoco has hecho nada nuevo para la convocatoria extraordinaria.

2022-02-07 21:28 UTC, NachoCarher commented on source/serie.py
> +from source.caracteristicas import Caracteristicas
source es el nombre del directorio en el que se guardan los fuentes, y yo no tomé la decisión de llamarlo así. De hecho en mi repo no figura con ese nombre. 

Me he encargado de referenciar a ese módulo porque es lo que me solicitó Pablo en su último comentario.

2022-02-07 21:37 UTC, NachoCarher commented on source/catalogo.py
> +  def __init__(self, series = []):
Le pregunté que si debido a no hacer los commits correctamente era motivo suficiente como para repetir el Objetivo. Y concluimos que no era necesario pues en los objetivos futuros demuestro que ya los hago siguiendo las buenas prácticas y son correctos.

Las caracteristicas de una serie están en el atributo características que corresponde a la clase Características y determinamos entre los dos que debia figurar así (desarrollado por @Parka015).

Cada serie cuenta con un identificador único definido en su clase correspondiente. Lo comentado no concierne a la clase Catálogo (asociada a #23), si no a la clase Serie.

2022-02-07 21:49 UTC, NachoCarher commented on source/serie.py
> +  def getLanzamiento(self):
@JJ de cara a la convocatoria extraordinaria trabajé en otra clase diferente bajo un issue asociado y habiendo leído toda la documentación sobre el hito, además de haber solucionado los errores destacados en la ordinaria e implementando lo que me solicitó Pablo en su comentario. 

Entiendo perfectamente lo de los getters y setters y el nombre y ámbito de los atributos, pero son puntualizaciones de los buenos procedimientos con el lenguaje de programación y los tendré en consideración. Profesor, he desarrollado lo suficiente e invertido en el objetivo las horas necesarios como para entenderlo y poder continuar con los siguientes.

2022-02-07 22:06 UTC, NachoCarher commented on source/serie.py
> +    self.identificador = iden                             # Codigo para identificar de forma unica cada serie
> Lo siento, no superas este objetivo. Habría sido conveniente que lo compartieras con la clase para que te ayudaran, o simplemente que me hicieras caso a los comentarios anteriores.

Profesor, he ido siguiendo paso a pasa cada uno de sus comentarios y tratándolos de satisfacer lo mejor posible. Le he preguntado en clase cómo proceder con el objetivo y cómo poder seguir avanzando. He estado bloqueado aquí por meses tratando de documentarme al máximo para pasarlo y contrastándolo con el de los compañeros. Además de haber estado hablando con Pablo sobre cómo proceder y qué implementar.

A mi parecer, y sin tratar de quitarle importancia al objetivo, el cómo he desarrollado los siguientes demuestra qué sé lo suficiente como para pasarlo y rogaría lo tuviese más en consideración pues sé que es atento y tiene esos aspectos en cuenta, pues imagino que le dará gran importancia a que el alumno demuestre una buena evolución.

2023-02-15 08:56 UTC, closed without merging